# Generated by Django 4.2.6 on 2023-12-04 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfirmationtoken',
            name='id',
            field=models.CharField(default='', editable=False, max_length=64, primary_key=True, serialize=False),
        ),
    ]
