# Generated by Django 4.2.6 on 2023-12-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_emailconfirmationtoken_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_profile',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
