# Generated by Django 4.2.6 on 2023-12-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_user_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_profile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
