# Generated by Django 4.2.6 on 2023-12-03 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
    ]
