# Generated by Django 4.2.6 on 2023-10-17 18:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cursos", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Artigo",
            new_name="Article",
        ),
    ]
