# Generated by Django 4.2.6 on 2023-11-19 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0002_remove_article_message_article_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="last_edition",
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
