# Generated by Django 4.2.6 on 2023-12-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_emphasis',
            field=models.BooleanField(default=False),
        ),
    ]
