# Generated by Django 4.2.6 on 2023-12-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_alter_article_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='activate',
            field=models.BooleanField(default=True),
        ),
    ]
