# Generated by Django 4.2.6 on 2024-02-09 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_is_emphasis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='activate',
            new_name='active',
        ),
    ]
