# Generated by Django 4.2.6 on 2024-02-12 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_article_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='active',
            new_name='is_active',
        ),
    ]
