# Generated by Django 4.2.6 on 2023-12-05 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_comment_of_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='last_edition',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='comment',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
