# Generated by Django 4.2.6 on 2023-12-05 13:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_comment_last_edition_comment_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='last_edition',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comment',
            name='publication_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
